"""initial

Revision ID: 99662dfb6315
Revises: 
Create Date: 2026-02-25 10:43:04.137537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99662dfb6315'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('role', sa.Enum('DEV', 'OPS', 'QA', 'PM', 'RD', 'COMMS', 'FIN', 'ADMIN', name='agentrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', name='agentstatus'), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('autonomy_level', sa.Enum('FULL', 'PREVIEW', 'APPROVAL', name='autonomylevel'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', 'COMPLETED', name='projectstatus'), nullable=True),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='projectpriority'), nullable=True),
    sa.Column('category', sa.Enum('CORE', 'LEGACY', 'PORTFOLIO', name='projectcategory'), nullable=True),
    sa.Column('github_repo', sa.String(length=255), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('COMMIT', 'PR', 'DEPLOY', 'RELEASE', 'COMMENT', 'TASK_CHANGE', 'AGENT_ACTION', name='activitytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('INDUSTRY', 'PERSONAL', 'CUSTOM', name='metriccategory'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('period', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='metricperiod'), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('BACKLOG', 'TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', 'CANCELLED', name='taskstatus'), nullable=True),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='taskpriority'), nullable=True),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('github_issue', sa.String(length=255), nullable=True),
    sa.Column('github_pr', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('metrics')
    op.drop_table('activities')
    op.drop_table('projects')
    op.drop_table('agents')
    # ### end Alembic commands ###
